livedrive_livedrive_api:
    resource: "@LivedriveLivedriveApiBundle/Controller/"
    type:     annotation
    prefix:   /

livedrive_product:
    resource: "@LivedriveProductBundle/Controller/"
    type:     annotation
    prefix:   /

